### ISSUE TITLE
Xcode beta 3 runtime issue

### ISSUE THREAD

**Issue by graham-perks-snap** [pmusolino/Wormholy#51]
Launching an app containing Wormholy results in an immediate abort with this message:

| Swift class extensions and categories on Swift classes are not allowed to have +load methods

**Comment by pmusolino** [comment]
Hi there. 
Are you using Swift 5? 

I have not yet tested Wormholy with Swift 5, it will be converted as soon as it is officially released.

**Comment by graham-perks-snap** [comment]
The error occurs in both a new template project created with Xcode beta, and in an existing project simply built with the beta. So Swift 4 and 5. The OS' loader generates the error and the app fails to even load, let alone run. The Swift version is immaterial.

I've not been able to trace down the `load` giving grief. 

I generated a Single View app from the template, close Xcode, `pod init`, added Wormholy to the Podfile. `pod install`, load the xcworkspace, run.

**Comment by maedewiza** [comment]
Any news on this?

**Comment by Coeur** [comment]
I was able to reproduce @graham-perks-snap steps.
Code builds fine, but running the app will cause an immediate issue.

Same issue whether using `use_frameworks!` or not.

Obviously related to one of the two `load` functions of the framework:
* either from [Wormholy+Foo.m](https://github.com/pmusolino/Wormholy/blob/master/Sources/Objc/Wormholy+Foo.m)
* or from [NSURLSessionConfiguration+Wormholy.m](https://github.com/pmusolino/Wormholy/blob/master/Sources/Objc/NSURLSessionConfiguration+Wormholy.m)

My guess is the it's the second file that is causing the issue, because `NSURLSessionConfiguration` is not a class belonging to Wormholy, so adding a `+load` in `NSURLSessionConfiguration` is forbidden.

**Comment by iiiCeBlink** [comment]
@graham-perks-snap hey, I just submit a PR https://github.com/pmusolino/Wormholy/pull/52 that can fix this issue. You can have a try.
