### ISSUE TITLE
package install fails

### ISSUE THREAD

**Issue by valexa** [pmusolino/Wormholy#81]
There seems to be a problem with the path in Package.swift

<img width="727" alt="Screenshot 2020-04-16 at 07 36 49 (2)" src="https://user-images.githubusercontent.com/108781/79422737-5203a480-7fb5-11ea-8b44-4f2b2bb549d1.png">

**Comment by pmusolino** [comment]
I share here the same answer that I published on your PR https://github.com/pmusolino/Wormholy/pull/82.
I never tried to use it, but I think that for now, the library can't support the Swift Package Manager, because it has heavy limitations that prevent adding files other than .swift files. In the case of Wormholy, it would not be possible to add all non-swift files (storyboards, xib, images, objective-c file, etc ...).
