### ISSUE TITLE
SPM error

### ISSUE THREAD

**Issue by furiosFast** [pmusolino/Wormholy#89]
hi,
when i try to add the framework with spm i get this error:

.../SourcePackages/checkouts/Wormholy/Package.swift: Source files for target Wormholy should be located under 'Sources/Wormholy', or a custom sources path can be set with the 'path' property in Package.swift

**Comment by pmusolino** [comment]
Hi there. For now, the library can't support the Swift Package Manager, because it has heavy limitations that prevent adding files other than .swift files. In the case of Wormholy, it would not be possible to add all non-swift files (storyboards, xib, images, objective-c file, etc ...). I will add support to SPM when they allow us to add external resources.
